### ISSUE TITLE
inference_pose_lifter_model raise IndexError.

### ISSUE THREAD

**Issue by AnxQ** [open-mmlab/mmpose#1003]
Following the pipeline in [body3d_two_stage_video_demo.py](https://github.com/open-mmlab/mmpose/blob/master/demo/body3d_two_stage_video_demo.py).
When some bboxes were drop due to threshold, will eventually cause the error in [here](https://github.com/open-mmlab/mmpose/blob/master/mmpose/apis/inference_3d.py#L171), when `_collate_pose_sequence()` try to extract a 2D pose of a target person which appears in the target frame but not appears in the frames around it.
The empty frame can be filled by 0 to temporarily solve the issue:
```python
pose_seq['keypoints'] = np.stack(
                [frame[idx]['keypoints'] if len(frame) > idx else np.zeros(pose_results[target_frame][0]['keypoints'].shape) for frame in pose_results])
```
But I don't think this is a good solution.

**Comment by ly015** [comment]
Thanks for the question. Here we try to handle two different settings: with or without track_id.

If the track_id is available, `_collate_pose_sequence` can handle the case that the target person is missing in some frames, and will fill the empty frame with information from its nearest available frame. Check this [code snippet](https://github.com/open-mmlab/mmpose/blob/c0d5e4c2b39a1ebeca4be2c6c6358c33a9a5012d/mmpose/apis/inference_3d.py#L176-L199)

On the other hand, if the track_id is unavailable, which is the case in this issue, we assume that all frames have a consistent number and order of persons. Otherwise, it's impossible to align person identities between different frames. So in this case we don't consider the missing of the target person.
