### ISSUE TITLE
rebase height

### ISSUE THREAD

**Issue by sunmengnan** [open-mmlab/mmpose#1051]
https://github.com/open-mmlab/mmpose/blob/f81cca5ff5da3e18f2e1a92dda66791a54987297/demo/body3d_two_stage_video_demo.py#L267

why do you minus the minimum value in z axis, why not the root joint, such as hip or pelvis?

**Comment by ly015** [comment]
Please note that here the z-axis corresponds to the height instead of the depth (The coordinate system has been changed [here](https://github.com/open-mmlab/mmpose/blob/f81cca5ff5da3e18f2e1a92dda66791a54987297/demo/body3d_two_stage_video_demo.py#L264) for visualization by matplotlib). And this rebasing is to land people on the ground, so we use the minimum z value (usually foot), instead of hip or pelvis.

**Comment by sunmengnan** [comment]
Thx., what is the unit of depth before the coordinate system been changed ? is it meter? Does it need to be normalized or something else?

**Comment by ly015** [comment]
Yes, the unit of the output is meter in all axes. No normalization is needed for the output.
It's worth noting that we provide an option to normalize the input to reduce the domain gap between testing and training data. Please check the argument [`--norm-pose-2d`](https://github.com/open-mmlab/mmpose/blob/f81cca5ff5da3e18f2e1a92dda66791a54987297/demo/body3d_two_stage_video_demo.py#L84).
