### ISSUE TITLE
compare mAP between coco and aic dataset with same model

### ISSUE THREAD

**Issue by canghaiyunfan** [open-mmlab/mmpose#1058]
In top-down method, the same model has larger gap between coco and aic dataset. for example, hrnet_w32 with 256x192 input size in coco dataset mAP is 0.746, but in aic dataset mAP is 0.323. 
I find that aic data is simple than coco, but why mAP is so small.

**Comment by jin-s13** [comment]
Because the evaluation metric (sigmas) of aic is much more strict than that of coco.

**Comment by canghaiyunfan** [comment]
Thanks for apply. 
1. Whether  sigmas can be modified?
2. In evaluate process, coco evaluate with use_area=True, while aic evaluate with use_area=False, how will this affect the mAP?

**Comment by jin-s13** [comment]
1. Whether sigmas can be modified? 
Currently, we use the official reported sigmas for evaluation. You can modify it here. 
https://github.com/open-mmlab/mmpose/blob/1e94844fb5f118f092ff198a5e51b67d8a71921c/configs/_base_/datasets/aic.py#L136

2. In evaluate process, coco evaluate with use_area=True, while aic evaluate with use_area=False, how will this affect the mAP?
Because the gt annotations (eg. CrowdPose, AIC) do not have 'area', so we have to set use_area=False.

**Comment by edwardnguyen1705** [comment]
Dear @jin-s13 ,

It seems that the download link of the https://github.com/AIChallenger/AI_Challenger_2017 is dead, do you have this dataset and could you share to me (GoogleDrive)?
