### ISSUE TITLE
Extracting keypoints of images from a custom corpus

### ISSUE THREAD

**Issue by garsontrier** [open-mmlab/mmpose#1103]
I am new to the pose estimation area and having a hard time navigating through docs.
I want to extract keypoints from a set of images by using pre-trained models provided by mmpose. 
I would be very grateful if you can address my questions:

1. I understand that I have to create a json file containing names and annotations of images. Since I am not going to train a new model, I feel like I don't have to fill in the annotation part of json file. Is this right?
2. Images in the dataset are in the size of 1280x720 and I don't see any pretrained models with this input size. Is there a way to infer keypoints from these images without resizing them? 
3. After loading an appropriate model and configuring dataset info class with mmpose/configs/_base_/datasets/coco_wholebody.py (I want my output to be in this format), can I simply use inference_bottom_up_pose_model function from the mmpose API?

Thanks in advance,

**Comment by ly015** [comment]
Hi, thanks for using mmpose. 

1. The json file is mainly for providing image paths and bbox information (for top-down method only). If you already have bbox annotation and hope to use a top-down pose estimation model, you would need to prepare the json file. Otherwise, you can inference pose from raw images by either combining a bbox detector and a top-down pose model (please check [top-down with mmdet](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#using-mmdet-for-human-bounding-box-detection)) or using a bottom-up pose model which is bbox-free (please check [bottom-up](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#2d-human-pose-bottom-up-image-demo))
2. You don't need to resize the image by yourself. The image will be resized automatically before being fed into the network, and the predicted keypoint coordinates will be processed to align with the original image size.
3. Yes you can use `inference_bottom_up_pose_model()`. Please check the bottom-up demo mentioned in 1 for the usage of this API. And please also note that 1) you need to pick up a model trained on coco-wholebody dataset (check out our [model zoo](https://mmpose.readthedocs.io/en/latest/papers/datasets.html#coco-wholebody-eccv-2020)); 2) The prediction is not exactly in the standard COCO format, so you probably need to add a few codes to convert the format.

**Comment by garsontrier** [comment]
Thank you for your quick response.
I am trying to apply the steps you explained, but still having problems.

1.  I modified the `configs/wholebody/2d_kpt_sview_rgb_img/associative_embedding/coco-wholebody/hrnet_w48_coco_wholebody_512x512.py`, I changed the workflow parameter to `[('val', 1)]`  and updated data paths for my json files. But, since I am using bottom-up approach, I am guessing json files won't be used anyway.
2. To use `inference_bottom_up_pose_model()`, I work with `demo/bottom_up_img_demo.py`. 
3. I use two different checkpoints, the first one is from pretrained parameter of the config file and the second one is taken from model zoo (w48+ model from the link you provided) for coco-wholebody dataset. I provide both links explicitly in the respective order: 

[https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w48-8ef0771d.pth](url)
[https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_coco_wholebody_512x512_plus-4de8a695_20210517.pth](url)

When I run the demo with the first checkpoint, it doesn't raise errors but warns me with the following message:
`The model and loaded state dict do not match exactly`
`unexpected key in source state_dict: conv1.weight, bn1.weight, bn1.bias, bn1.running_mean, ...`
`missing keys in source state_dict: backbone.conv1.weight, backbone.bn1.weight, backbone.bn1.bias, backbone.bn1.running_mean, ...`
Code works without any other warnings but returns an empty list for `pose_results`. Since the keys don't match, I guess it can't initialize the model with pretrained weights.

For the other checkpoint, it raises the following error during inference:
`File "/home/mansur/mmpose/mmpose/apis/inference.py", line 568, in inference_bottom_up_pose_model`
    `keep = oks_nms(pose_results, pose_nms_thr, sigmas=None)`
  `File "/home/mansur/mmpose/mmpose/core/post_processing/nms.py", line 116, in oks_nms
    sigmas, vis_thr)`
  `File "/home/mansur/mmpose/mmpose/core/post_processing/nms.py", line 81, in oks_iou`
    `e = (dx**2 + dy**2) / vars / ((a_g + a_d[n_d]) / 2 + np.spacing(1)) / 2`
`ValueError: operands could not be broadcast together with shapes (133,) (17,) `
 I believe this is due to the discrepancy between config file and model parameters, one being for coco-wholebody and the other for coco body dataset.
 
I feel like I am making a simple mistake, but couldn't figure it out at the moment. What would you suggest I do?

Thanks,

**Comment by ly015** [comment]
For the first checkpoint, the warnings can be just ignored. (The warnings are raised because when loading the backbone weights, the FC layers at the end are discarded).

For the second checkpoint, the error is caused by a bug that the COCO sigmas are hard-coded in the demo which conflicts with the COCO-wholebody model. This has been fixed in #1101 and will be merged in a few days.

**Comment by ly015** [comment]
#1101 has been merged into master.

**Comment by garsontrier** [comment]
Problem resolved. Works like a charm.

Thanks,
