### ISSUE TITLE
How to run the 3D Hand Estimation Image Demo

### ISSUE THREAD

**Issue by koegl** [open-mmlab/mmpose#1456]
I'm having trouble running the [3D Hand Estimation Image Demo](https://mmpose.readthedocs.io/en/latest/demo.html#d-hand-estimation-image-demo)

I installed mmpose with pip and verified the installation as shown [here](https://mmpose.readthedocs.io/en/v0.27.0/install.html#verify-the-installation) - everything worked.

Now I wanted to try to estimate the 3D pose as shown in the tutorial linked above, but I don't know how to get the "gt json." How can I get this json file?

Or in general, how can I estimate the 3D pose of a hand with an image of a hand?

**Comment by zengwang430521** [comment]
Hi, you may need to detect the hand box first and then organize the detection result in the format like the [example file](https://github.com/open-mmlab/mmpose/issues/1456).

Actually, I do not recommend you to run the interhand3d demo with only an image. Because the interhand3d model requires camera parameters and root joint depth to output the final result. It's not a good choice for the demo.
