### ISSUE TITLE
my own dataset

### ISSUE THREAD

**Issue by jojolee123** [open-mmlab/mmpose#1471]
i wanna to detect ship keypoint using mmpose.there are four defined keypoints. I rewrite the format of MPII dataset config file to adapt my dataset. I can train and test,but the result is strange. i guess there are problems during training process.
i just modify the hourglass52_mpii_256*256.py and /_base_/datasets/mpii.py  Are there other place need to be modified?

**Comment by liqikai9** [comment]
Did you modify the [num_output_channels](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py#L26) in the config as well? Because the number of keypoints has changed, you may also need to change the number of output channels, which corresponds to the number of keypoints you need.

**Comment by jojolee123** [comment]
> 1. This file `mpii_gt_val.mat` should be your own annotation file, and it is used in evaluation.
> 2. The parameter "center" and "scale" controls the affine transform to the image to make input. Please note that in MPII dataset, the scale is normlaized by a factor 200.
> 
> @jin-s13 Could you please help take a look?



> 1. This file `mpii_gt_val.mat` should be your own annotation file, and it is used in evaluation.
> 2. The parameter "center" and "scale" controls the affine transform to the image to make input. Please note that in MPII dataset, the scale is normlaized by a factor 200.
> 
> @jin-s13 Could you please help take a look?

I know it should be the data. The number of my images is too small. I readjusted my learning rate, and it worked
thank you!

**Comment by zbl929** [comment]
您好，船舶关键点检测您用的是哪个模型，效果怎么样？
