### ISSUE TITLE
body3d Symmetry Issue

### ISSUE THREAD

**Issue by iulsko** [open-mmlab/mmpose#1478]
Hi, i have an issue with the 3d plot created from a video using _body3d_two_stage_video_demo.py_. 

The left side (left shoulder, knee, hip etc.) of the skeleton is mixed up with the right side. This becomes obvious when you create an interactive plot with the 3D points and rotate it, where you can see that the location of the points physically does not make sense. 

This happens for every video that I have tried. I assume the issue is with the `keypoint_info` of the Body3DH36MDataset, where left- and right- keypoints should be swapped.

Could someone verify it or am I missing something?

**Comment by ly015** [comment]
Thanks for the feedback. We will check it asap.

**Comment by iulsko** [comment]
> Thanks for the feedback. We will check it asap. Could you please provide the command line and the results?

ok, so the command line:

`python mmpose/demo/body3d_two_stage_video_demo.py mmdetection/configs/yolox/yolox_x_8x8_300e_coco.py https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288_dark-e881a4b6_20210203.pth mmpose/configs/body/3d_kpt_sview_rgb_img/pose_lift/h36m/simplebaseline3d_h36m.py https://download.openmmlab.com/mmpose/body3d/simple_baseline/simple3Dbaseline_h36m-f0ad73a4_20210419.pth --out-video-root <output dir> --thickness 2 --kpt-thr 0.5 --bbox-thr 0.7 --video-path <input.mp4> --device cuda`

the results are simply the logged 3D keypoints, so i log `res` after line 347 and `res["keypoints_3d"]` are the ones that i visualize.

**Comment by liqikai9** [comment]
@iulsko I have tried the same command like yours:
```python
python mmpose/demo/body3d_two_stage_video_demo.py mmdetection/configs/yolox/yolox_x_8x8_300e_coco.py https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288_dark-e881a4b6_20210203.pth mmpose/configs/body/3d_kpt_sview_rgb_img/pose_lift/h36m/simplebaseline3d_h36m.py https://download.openmmlab.com/mmpose/body3d/simple_baseline/simple3Dbaseline_h36m-f0ad73a4_20210419.pth --out-video-root mmpose/vis_results/ --thickness 2 --kpt-thr 0.5 --bbox-thr 0.7 --video-path https://user-images.githubusercontent.com/87690686/164970135-b14e424c-765a-4180-9bc8-fa8d6abc5510.mp4 --device cuda --rebase-keypoint-height
```

And here is my output result (you can download it to have a look). The results look fine. Would you mind sharing your input video so that I can run for a look?

https://user-images.githubusercontent.com/87690686/178699017-c2d2f67b-781f-4934-a9cd-221a5b8b2014.mp4

**Comment by iulsko** [comment]
hi @liqikai9, thanks for reaching out!

so yes, the code works and i can generate the same video as you do but the symmetry issue exists there as well. i am using the keypoint information found in `pose_lift_model.cfg.data["train"]["dataset_info"]["keypoint_info"]`

1. i output the 3D coordinates of the right/left hip and right/left shoulder with this print statement (frame 0):
```
print("right hip", keypoints_3d[1,:]) >>> [ 0.10672681 -0.05491869  0.83654296]
print("left hip", keypoints_3d[4,:]) >>> [-0.10672686  0.05491847  0.83488935]
print("right shoulder", keypoints_3d[14, :]) >>> [ 0.14318195 -0.18819898  1.2919736 ]
print("left shoulder", keypoints_3d[11, :]) >>> [-0.14618593 -0.09089883  1.3007789 ]
```
since the x-axis is pointing to the left in our visualization, the right hip/shoulder should have a larger value in the x-coordinate -> so far so good.

but once the subject starts turning, we see discrepancies, as in the image below, where the left leg appears to be in front of the right leg in the 3D vis (you can see that the green keypoint appears in the front)
<img width="1254" alt="Screen Shot 2022-07-13 at 3 07 50 PM" src="https://user-images.githubusercontent.com/31110373/178817825-a26c6b6f-4b59-4851-92e5-6c9647cb93bf.png">

or, in the last frame of the video, we would expect the left foot to be further away from us (y coordinate should be smaller), which is not the case:
```
print("right foot", keypoints_3d[3, :]) >>> [0.00618519 0.01175313 0.        ]
print("left foot", keypoints_3d[6, :]) >>> [0.1488405  0.2993712  0.05579627]
```

so the x component seems to be fine but not the depth

**Comment by liqikai9** [comment]
Hi @iulsko, you are really a careful and rigorous observer. 

It is worth mentioning that the keypoints for 2D visualization (which is shown on the left of the above picture) is predicted by a 2D pose detector, as the config in the command like `configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py`.

And the keypoints for 3D visualization (which is shown on the right of the above picture) is predicted by a PoseLifter, as the config in the command like `configs/body/3d_kpt_sview_rgb_img/pose_lift/h36m/simplebaseline3d_h36m.py`.

So the left picture and the right picture do not share the same prediction keypoint results.


> print("right foot", keypoints_3d[3, :]) >>> [0.00618519 0.01175313 0.        ]
> print("left foot", keypoints_3d[6, :]) >>> [0.1488405  0.2993712  0.05579627]

As you have already pointed out, in the last frame, the y-coordinate of left foot is larger than the y-coordinate of right foot, so it appears in the right picture that the left foot is closer to us, as shown on the right picture:

![image](https://user-images.githubusercontent.com/87690686/178900825-5a226c7b-07b9-4669-820b-06147ebe4ecc.png)

This indicates that the 3D visualization results are **aligned** with the model prediction results.

However, from the left picture, we would expect the left foot to be further away from us in the 3D visualization result. 

I think this is due to the **prediction error** introduced by the PoseLifter model, especially when the object in the video is moving fast. And the keypoint indices and symmetry should be fine.

**Comment by iulsko** [comment]
Hi @liqikai9,

thank you so much for such detailed feedback! it helped so much! :)
