### ISSUE TITLE
3d huaman keypoint ,the Gpu seems dose not work

### ISSUE THREAD

**Issue by graceforlife** [open-mmlab/mmpose#1733]
![12](https://user-images.githubusercontent.com/115878494/196078048-b66973e0-349f-4efb-b82d-a724c4e9bbe7.png)
When I checked my GPU in the first phase, the occupancy rate was 60%, while in the second phase, the occupancy rate was 0. I doubt that the program did not use GPU acceleration in the second phase. You can also see the difference from task/s

**Comment by ly015** [comment]
Thanks for the feedback. We will look into this issue asap.

**Comment by graceforlife** [comment]
> Thanks for the feedback. We will look into this issue asap.

okok，also thanks u~,and the erro hanppended in the 3d human keypoint with the vedios

**Comment by ly015** [comment]
@graceforlife We have checked this issue. The low GPU occupancy rate in the 2nd stage is because the pose lifting model is a small network and the major workload stays in data I/O and post-processing. You can remove the post-processing and visualization code and the inference of the 2nd stage will be much faster.

**Comment by graceforlife** [comment]
> @graceforlife We have checked this issue. The low GPU occupancy rate in the 2nd stage is because the pose lifting model is a small network and the major workload stays in data I/O and post-processing. You can remove the post-processing and visualization code and the inference of the 2nd stage will be much faster.

好的，谢谢您~
