### ISSUE TITLE
top_down_img_demo_with_mmdet.py

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmpose#1790]
In the det_checkpoint file top_down_img_demo_with_mmdet.py, if I want to train my own data, then in addition to training the attitude estimation model, I also need to train a target detection model in advance to get the weight file

**Comment by Ben-Louis** [comment]
Hi, if your target objects are included in [COCO category](https://gist.github.com/AruniRC/7b3dadd004da04c80198557db5da4bda), you can directly use detectors trained on COCO such as the one in the following command
```bash
python demo/top_down_img_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    ...
```
Otherwise, you may need to train an object detector with [MMDetection](https://github.com/open-mmlab/mmdetection) on your data.
