### ISSUE TITLE
MPII dataset for Bottom up models

### ISSUE THREAD

**Issue by SanJotter** [open-mmlab/mmpose#182]
Hi. Great work from your side.
I wanted to know whether there was any hard reason for not training MPII dataset for Bottom up approaches?

**Comment by innerlee** [comment]
btw we have noticed the request in the meta issue

**Comment by innerlee** [comment]
since we are here, a quick survey: do you want pre-trained models, or just code/script for training?

**Comment by jin-s13** [comment]
Hi SanJotter,

This repo currently only supports MPII single-person dataset (for Top-down), but the multi-person part (for Bottom-up) is not available yet. To support MPII dataset for Bottom-up approaches, one needs to process the original .mat file and generate the json file for training/evaluation. 

This is not hard. But it would take a while. We will consider prioritizing this.

Any help is welcome~

**Comment by SanJotter** [comment]
Hi @jin-s13 , I believe this is one important.
Please find this link where these guys have already generated json files for training/evaluation (Google drive and OneDrive is available):
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch#data-preparation

@innerlee, as for the survey, I wanted a pre-trained model. But I now know it gonna take time with respect to reply from @jin-s13 .

**Comment by jin-s13** [comment]
Hi @SanJotter,
Thanks for the reply. We have also noticed this download link. But unfortunately, their train/evaluation json files are only for MPII **single-person** dataset, which are not suitable for bottom-up methods.

**Comment by SanJotter** [comment]
I might sound a noob here but may I know why Bottom-up methods cannot support single-person dataset?

**Comment by SanJotter** [comment]
This guy here has converted json for mpii multi-person dataset (Not sure the format is same as you expected):
https://github.com/bearpaw/pytorch-pose/blob/master/TRAINING.md#mpii-human-pose-dataset


Would still be expecting an answer from you as to why Bottom-up methods cannot support single-person dataset?

**Comment by jin-s13** [comment]
For bottom-up methods, the basic assumption is that there are multiple people in the images. These bottom-up methods typically consist of two stages, i.e. keypoint detection stage & keypoint grouping stage. In the keypoint detection stage, all keypoints of all people are detected at once; While in the grouping stage, the keypoints are grouped to different individuals. 

If we already know that the images only contain single person, then the grouping stage is useless (since all keypoints belong to the same person, no need to group). And in such cases, the bottom-up approaches degenerate to top-down approaches, which assumes that there is only one person in the input image. 

Also note that according to the official evaluation protocol, for mpii single-person dataset, the location and scale of the target person is provided. And we need to estimate the pose of that specified person, which is the setting for top-down approaches not bottom-up approaches.

**Comment by SanJotter** [comment]
@jin-s13 , Couldn't have got a better explanation than this one. Thank you.

Everything is making sense now but one:
For top down (single person - mpii) we still have to detect bbox of person in the new images before pose estimation, which itself is an overhead process considering only single person is present in the image.

**Comment by jin-s13** [comment]
Aha, generally we need to detect the human bounding boxes for top-down approaches. And yes, the human detection part costs a lot of time. 

But for the evaluation of mpii single-person dataset, since the ground-truth(gt) location & scale is provided for each person, we can simply use the gt boxes  : )   In other words, no human detection is needed for mpii dataset evaluation.
