### ISSUE TITLE
Do I need to retrain Voxelpose for different camera parameters?

### ISSUE THREAD

**Issue by OmkarKabadagi5823** [open-mmlab/mmpose#1821]
I want to use the Voxelpose model in real-time for my own scene. My setup has three cameras placed at about 90 degrees to each other in a circular setup facing the center of the circle. I calibrated the intrinsic and the extrinsic for all the cameras. I also made sure my translation values are in _cm_ and not _mm_ in the json file . But I get no pose estimations at all for my input. 

So I tried an experiment by using the cameras from panoptic dataset similar to my setup and used their calibration values instead and I am getting some pose estimations although they are obviously not accurate. I am pretty sure that my calibration values are correct, so I am not sure if the pretrained model is baised towards the camera parameters of panoptic dataset. 

I did go through the #1310 issue, but I am asking the question again because I had one more question to add to it.
I have a question regarding the function `get_panoptic_camera_parameters` with specifically trying to understand the role of function argument `M`

```python
def get_panoptic_camera_parameters(cam_file,
                                   camera_names,
                                   M=[[1.0, 0.0, 0.0], [0.0, 0.0, -1.0],
                                      [0.0, 1.0, 0.0]]):
    with open(cam_file) as cfile:
        calib = json.load(cfile)

    M = np.array(M)   # what is the significance of M
    cameras = {}
    for cam in calib['cameras']:
        if cam['name'] in camera_names:
            sel_cam = {}
            R_w2c = np.array(cam['R']).dot(M) # M used here
            T_w2c = np.array(cam['t']).reshape((3, 1)) * 10.0  # cm to mm
            R_c2w = R_w2c.T
            T_c2w = -R_w2c.T @ T_w2c
            .
            .
            .
```
What is the significance of the matrix `M`. To me it just seems like a swapping the axes which shouldn't affect the pose estimations. So in another experiment I used the panoptic dataset provided, and commented the dot with matrix M.

```python
R_w2c = np.array(cam['R']) #.dot(M)
```
With this change the pose estimations were empty for the panoptic dataset too. So how is `M` affecting the input?

**Comment by liqikai9** [comment]
For The matrix `M`, it will not affect the pose estimation results. It is used for translating the coordinate system and you can see the related issue here: https://github.com/microsoft/voxelpose-pytorch/issues/11#issuecomment-737944270.

**Comment by OmkarKabadagi5823** [comment]
I understood the role of `M`, my issue is that unlike you mention `M` should not affect pose estimation results, it is getting affected.
For panoptic dataset, below are results with and without M

`R_w2c = np.array(cam['R']).dot(M)`
![0_2_2d](https://user-images.githubusercontent.com/55598261/202993698-f613aa3a-0856-4a77-b44b-fd137ad03906.jpg)

`R_w2c = np.array(cam['R'])`
![0_2_2d](https://user-images.githubusercontent.com/55598261/202993791-1783e4db-039d-4a3f-951a-59fc1caeecd1.jpg)

As you can see by not multiplying with M, I am not getting any results.

**Comment by liqikai9** [comment]
@OmkarKabadagi5823 Sorry for that I did not understand your question very well before. 

In VoxelPose model, the cases with and without `M` will result in different camera parameters. And this will affect the projection relationship when projecting the 3D grid into the specific 2D pixel plane and gather the featmaps around the projection point, as shown in this [code](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/detectors/multiview_pose.py#L94-L98), and this will lead to different 3D feature volumes and further will result in different output 3D keypoints cooridinates.  Hence, the matrix M will affect the model's output. 

So if you want to run inference with the trained VoxelPose model, you should also adapt the operation with `.dot(M)` because the model was trained with multiplying `M`.

**Comment by OmkarKabadagi5823** [comment]
Thanks @liqikai9 . I was suspecting something like that. Thank you for your clarification

**Comment by OmkarKabadagi5823** [comment]
I have one more question. From what I have realised, it is recommended to retrain (or tune) the network to the specific application where it is being deployed. 

I am not clear on how should I prepare my dataset for training the Voxelpose model, as getting the 3D ground truths is a difficult task. Could you elaborate on the procedure for training?

**Comment by liqikai9** [comment]
@OmkarKabadagi5823 In short, to train a VoxelPose model, you need to prepare your own images from different cameras and the corresponding calibrated camera pameters. 

I am afraid that the 3D ground truths are necessary. However, since the 3D keypoint cooridinates are difficult to get, in some cases, if you already have the 2D ground truth keypoint positions under different views, you may reconctruct the 3D  keypoint positions using some approximation algorithm like [triangulation](https://en.wikipedia.org/wiki/Triangulation). 

However, if the keypoints are occluded or are annotated with noises under some views, it may be difficult to get accurate 2D keypoint annottaions and thus the 3D annotations are not accurate.

For your information, you can also refer to to the typical [CMU Panoptic dataset](https://openaccess.thecvf.com/content_iccv_2015/html/Joo_Panoptic_Studio_A_ICCV_2015_paper.html) for more detail about the data preparation.

**Comment by OmkarKabadagi5823** [comment]
Alright. Thank you for your help .

**Comment by Taylorminer** [comment]
@OmkarKabadagi5823 Hi,have you tested voxelpose successfully in your scene ? How do you calibrate the camer ?
