### ISSUE TITLE
How to train custom data & annotation without bbox?

### ISSUE THREAD

**Issue by Jeong-Bin** [open-mmlab/mmpose#1869]
My project is to get x, y ,z keypoint-values of body, hands and foot from 2D videos.
And also I'm trying to train by my custom data & annotaion.
In this process, I have 2 questions.

First, Which model should I follow? [2D Human Whole-Body Pose Top-Down Video Demo](https://mmpose.readthedocs.io/en/latest/demo.html#d-human-whole-body-pose-top-down-video-demo)?
or [3D Human Pose Two-stage Estimation Video Demo](https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-two-stage-estimation-video-demo)?
 
Second question is about bounding box.
My json annotation files don't have the 'bbox'...
How to train customize dataset without bounding box?
Do I just change my json file like COCO format without bbox? 
or just create and add custom_config.py like [this tutorial](https://mmpose.readthedocs.io/en/latest/tutorials/2_new_dataset.html#create-a-custom-dataset-class)?

I referred to this issue(#1473), but it is still difficult because I'm not used to this Human Pose task.😢

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. For your questions,

1) Since you want to estimate 3D human pose, you could try the later one, [3D Human Pose Two-stage Estimation Video Demo](https://mmpose.readthedocs.io/en/latest/demo.html#d-human-pose-two-stage-estimation-video-demo)

2) Whether to use bounding box depends on the pose model you want to use. 
If you want to train a bottom-up pose estimator, bounding boxes are neglectable in your json file. 
If you want to train a top-down pose estimator, which is adopted by the above demo script, bounding boxes are necessary in this case. You may calculate the bounding box via keypoints as following: 
`bbox=[x, y, w, h]` where
    - `x` is the x-coordinate of the left-most visible keypoint
    - `y` is the y-coordinate of the top visible keypoint
    - `w` is the difference of x-coordinate between the right-most and the left-most visible keypoint
    - `h` is the difference of y-coordinate between the bottom and the top visible keypoint

**Comment by Jeong-Bin** [comment]
Thank you for your kind help!
