### ISSUE TITLE
MMPose_Tutorial.ipynb error in a particular cell

### ISSUE THREAD

**Issue by SoumyajitMukherjee-droid** [open-mmlab/mmpose#1918]
the below command 

"from mmpose.apis import inference_top_down_pose_model,init_pose_model,vis_pose_result, process_mmdet_results"

throws error. 

PFB error details.
[/usr/local/lib/python3.8/dist-packages/xtcocotools/mask.py](https://localhost:8080/#) in <module>
      1 __author__ = 'tsungyi'
      2 
----> 3 import xtcocotools._mask as _mask
      4 
      5 # Interface for manipulating masks stored in RLE format.

xtcocotools/_mask.pyx in init xtcocotools._mask()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

I tried to upgrade numpy as well, but it did not work.

**Comment by jin-s13** [comment]
Indeed, installing with numpy>=1.20.0 should work.

**Comment by yanavdsande** [comment]
HI! I also ran into this problem. I checked the requirement files and changed all the numpy to numpy>1.20.0 manually  - it is a bit curious because my numpy version is 1.24.0, which is higher than 1.20.0. But it didn't work..  

If you want to reproduce, I used your mmpose_tutorial notebook. 

I also tried the following (unfortunately without luck): 
forge numpy to be 1.22.0 by adding !pip install numpy=1.22.0 
changed python 3.8 to 3.6 
reinstalled pycocotools with the flag:  --no-binary pycocotools


Thank you in advance!

**Comment by il-yanko** [comment]
I got the same mistakes as @yanavdsande while was trying to run the current version of MMPose. My build was based on mmpose_tutorial notebook and worked just a month ago without any issues or warnings.

**Comment by Ben-Louis** [comment]
Please refer to https://github.com/open-mmlab/mmpose/issues/1939

**Comment by JiaBob** [comment]
Any existing answer did not work for me. I solved this by upgrading all numpy, scipy and numba to the latest version.
