### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by qiuzhongwei-USTB** [open-mmlab/mmpose#1929]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/34059431/211846909-ec6d15d1-5d01-4e2b-b5b7-7909175c8fbe.png">

in line 99:
     img_path = data_batch[0]['data_sample'].get('img_path')

I find that data_batch is a dict, including         #dict_keys(['inputs', 'data_samples']).

**Comment by Ben-Louis** [comment]
Thank you very much for your kind reminder. This bug has been fixed in branch `dev-1.x` (https://github.com/open-mmlab/mmpose/pull/1800) but not in branch `1.x`. You can modify the code following https://github.com/open-mmlab/mmpose/pull/1800 to fix the problem. Moreover, it would be much appreciated if you could raise a PR to fix this bug in branch `1.x`
