### ISSUE TITLE
question regarding datasets _xywh2cs on scale and std

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmpose#205]
I had some questions regarding the bounding box conversion from xywh to center and scale.

Looking at panoptic/coco/freihand/onehand10k they all have different values when modifying the scale. 

```python
    def _xywh2cs(self, x, y, w, h):
        """This encodes bbox(x,y,w,w) into (center, scale)

        Args:
            x, y, w, h

        Returns:
            center (np.ndarray[float32](2,)): center of the bbox (x, y).
            scale (np.ndarray[float32](2,)): scale of the bbox w & h.
        """
        aspect_ratio = self.ann_info['image_size'][0] / self.ann_info[
            'image_size'][1]
        center = np.array([x + w * 0.5, y + h * 0.5], dtype=np.float32)

        if (not self.test_mode) and np.random.rand() < 0.3:
            center += 0.4 * (np.random.rand(2) - 0.5) * [w, h]

        if w > aspect_ratio * h:
            h = w * 1.0 / aspect_ratio
        elif w < aspect_ratio * h:
            w = h * aspect_ratio

        # pixel std is 200.0
        scale = np.array([w / 200.0, h / 200.0], dtype=np.float32)
       ### HERE ###
        scale = scale * 1.76

        return center, scale
```

coco - 1.25
panoptic - 1.76
freihand - 0.8
onehand10k -1.25

How where these values chosen? Also is the pixel std a known value the way that ImageNet mean/std are known? How was this value found?

Also why are you dividing by the pixel std rather than just leaving it w and h. I see that when doing the topdown affine transformation to crop/augmentent images you just multiply in the std anyway, so I don't understand the purpose

```python
# pixel_std is 200.
scale_tmp = scale * 200.0
```

Thanks for the help

**Comment by jin-s13** [comment]
1. Why the scales for different datasets are different?
1) coco and onehand10k, bounding boxes are manually annotated. We simply use `scale=1.25` to include some context.
2) panoptic dataset does not have such annotations. We use the closest box covering the hand keypoints as its approximate bounding box (which is smaller). We should use a larger scale, so we use `scale=1.76`.
3) For freihand, the hands are cropped and centered. We directly use the whole image (224x224) as the bounding box (which is much larger).  We should use a smaller scale, so we use `scale=0.8`.

2. Why do we need `pixel_std`?
Some datasets (such as mpii, mpii-trb) do not provide w and h, they simply provide center/scale. And their scales are calculated by `w/200` and `h/200`. In order to be compatible to both cases, we also set `pixel_std=200`.

**Comment by innerlee** [comment]
maybe we can add this info near those magic numbers

**Comment by jin-s13** [comment]
Also note that, we do not carefully tune these super-parameters. Just rule of thumb.

@innerlee  yes, it seems better to add this info in the codes.

**Comment by pablovela5620** [comment]
Great, thank you for clarifying. So its basically a hyperparameter to ensure the minimum sized bounding box includes all hand keypoints rather than a box that is too big/small

**Comment by jin-s13** [comment]
Info about these hyper-parameters are added, in #202
