### ISSUE TITLE
 mmpose 1.x run demo issue.

### ISSUE THREAD

**Issue by nlxxWangYH** [open-mmlab/mmpose#2054]
When I run the QUICK RUN "python demo/image_demo.py \
    tests/data/coco/000000000785.jpg \
    configs/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_coco_256x192_rle-2ea9bb4a_20220616.pth" of the MMPose Document, the code can't stop.

(OpenMMLab) [***@*** mmpose]$ python demo/image_demo.py \
>     tests/data/coco/000000000785.jpg \
>     configs/body_2d_keypoint/topdown_regression/coco/td-reg_res50_rle-8xb64-210e_coco-256x192.py \
>     https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_coco_256x192_rle-2ea9bb4a_20220616.pth
/home/***/OpenMMLab/mmcv/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
03/14 00:23:14 - mmengine - WARNING - The "model" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
03/14 00:23:15 - mmengine - WARNING - The "KEYPOINT_CODECS" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_coco_256x192_rle-2ea9bb4a_20220616.pth
Downloading: "https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_coco_256x192_rle-2ea9bb4a_20220616.pth" to /home/***/.cache/torch/hub/checkpoints/deeppose_res50_coco_256x192_rle-2ea9bb4a_20220616.pth
100.0%
03/14 00:23:26 - mmengine - WARNING - The "dataset" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
03/14 00:23:29 - mmengine - WARNING - The "visualizer" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
03/14 00:23:29 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
03/14 00:23:29 - mmengine - WARNING - The "transform" registry in mmpose did not set import location. Fallback to call `mmpose.utils.register_all_modules` instead.
03/14 00:23:29 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
03/14 00:23:29 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
/home/***/OpenMMLab/mmengine/mmengine/visualization/visualizer.py:741: UserWarning: Warning: The bbox is out of bounds, the drawn bbox may not be in the image
  warnings.warn(
/home/***/OpenMMLab/mmengine/mmengine/visualization/visualizer.py:812: UserWarning: Warning: The polygon is out of bounds, the drawn polygon may not be in the image
  warnings.warn(

**Comment by Tau-J** [comment]
Thanks for using MMPose. If you are using opencv without a GUI (e.g. running on a Server), the demo script will get stuck. You can set `show=False` [here](https://github.com/open-mmlab/mmpose/blob/c6de39ce8984e90f4f92690af30cae86e080a1fb/demo/image_demo.py#L61) to solve this problem.

**Comment by nlxxWangYH** [comment]
> Thanks for using MMPose. If you are using opencv without a GUI (e.g. running on a Server), the demo script will get stuck. You can set `show=False` [here](https://github.com/open-mmlab/mmpose/blob/c6de39ce8984e90f4f92690af30cae86e080a1fb/demo/image_demo.py#L61) to solve this problem.

Thank you very much for your answer, the issue was solved.

**Comment by ruezzZZ** [comment]
I get an error when I run the mmpose 2.x demo. When I run the QUICK RUN " **demo\image_demo.py tests\data\coco\000000000785.jpg td-hm_hrnet-w48_8xb32-210e_coco-256x192.py td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth --out-file vis_results.jpg --draw-heatmap**" of the MMPose Document, the code can't stop.

**(mmpose_py38) D:\CodeTest\Code\gitclone\mmpose>python demo\image_demo.py tests\data\coco\000000000785.jpg td-hm_hrnet-w48_8xb32-210e_coco-256x192.py td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth --out-file vis_results.jpg --draw-heatmap
D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "demo\image_demo.py", line 8, in <module>
    from mmpose.apis import inference_topdown, init_model
  File "d:\codetest\code\gitclone\mmpose\mmpose\apis\__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottomup,
  File "d:\codetest\code\gitclone\mmpose\mmpose\apis\inference.py", line 17, in <module>
    from mmpose.models.builder import build_pose_estimator
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\__init__.py", line 8, in <module>
    from .heads import *  # noqa
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\heads\__init__.py", line 11, in <module>
    from .transformer_heads import EDPoseHead
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\heads\transformer_heads\__init__.py", line 2, in <module>
    from .edpose_head import EDPoseHead
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\heads\transformer_heads\edpose_head.py", line 14, in <module>
    from mmcv.ops import MultiScaleDeformableAttention
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。**
