### ISSUE TITLE
browse dataset

### ISSUE THREAD

**Issue by HyoKong** [open-mmlab/mmpose#2074]
May I ask where is the browse_dataset.py in tools/misc? I want to visualize the training dataset but cannot find the script.

Thank you so much for your help!

**Comment by Tau-J** [comment]
https://github.com/open-mmlab/mmpose/blob/1.x/tools/misc/browse_dataset.py

**Comment by HyoKong** [comment]
> https://github.com/open-mmlab/mmpose/blob/1.x/tools/misc/browse_dataset.py

Thank you so much for your reply!

**Comment by HyoKong** [comment]
do i need to re-git clone all the repo from 1.x branch?

**Comment by Tau-J** [comment]
Sure, 1.x branch is based on MMPose 1.0, while master branch is based on MMPose 0.29, they are not compatible.

We recommend 1.x for beginners, because 
  1) the framework is better designed;
  2) the [documentation](https://mmpose.readthedocs.io/en/dev-1.x/overview.html) is richer and clearer, especially tutorials for beginners; 
  3) The future development of MMPose will focus on 1.x, so new features will be first added into 1.x; So unless you are looking for some models or features only supported in 0.x, we recommend using 1.x. And all features in 0.x will be supported in 1.x in the next few months.

**Comment by HyoKong** [comment]
ok, well noted. Thank you so much!
