### ISSUE TITLE
MMPose models licensing

### ISSUE THREAD

**Issue by lipo5476** [open-mmlab/mmpose#2106]
Hello,

I found your open project very useful to experiment with new neural networks and features.
I would like to know if it is possible to use your pre-trained models, specifically **mobilenetv2_coco_256x192** and **seresnet50_coco_256x192** from MMPose, converted into ONNX models, in a commercial application. As they were trained on COCO dataset and MMPose is under the Apache-2.0 license, I suppose it is legal. However, I want to be sure, before using it that way.
So, can your pre-trained models be used in a commercial application, as they are? And under what license? 

Thank you in advance for your reply.

Lipo

**Comment by ly015** [comment]
To the best of our knowledge, the commercial use of pre-trained models should be allowed since both the COCO dataset and the MMPose project are licensed with permission for commercial use. Nevertheless, you may need to consult legal experts for a definitive answer. The discussion here (https://github.com/pytorch/vision/issues/2597) could be helpful.

**Comment by lipo5476** [comment]
Thank you for your response.
