### ISSUE TITLE
Numpy C-API incompatibility when trying to re-implement the Colab notebook tutorial

### ISSUE THREAD

**Issue by anantgrover123** [open-mmlab/mmpose#2114]
When trying:
from mmpose.apis import (inference_top_down_pose_model, init_pose_model, vis_pose_result, process_mmdet_results)
Colab throws the following error:
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

This is the link of the Colab Notebook I was trying to implement:https://colab.research.google.com/github/open-mmlab/mmpose/blob/master/demo/MMPose_Tutorial.ipynb
You can try running the cells one by one and understand the issue more thoroughly

I've tried upgrading numpy to its latest version but it still doesn't work.

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose. The problem you're experiencing might be due to a discrepancy between the Numpy version on the system where the software or library was compiled and the one on your current system. To resolve this, identify the incompatible package for your platform and reinstall it. For example, others have faced a similar Numpy error in the tutorial notebooks, which can be fixed by installing xtcocotools directly from the source, rather than using the package (see https://github.com/open-mmlab/mmpose/issues/1939).

**Comment by anantgrover123** [comment]
Thanks a lot. It works now!!!
