### ISSUE TITLE
ImportError: cannot import name 'inference_bottom_up_pose_model' from 'mmpose.apis'

### ISSUE THREAD

**Issue by dkobayas-cyber** [open-mmlab/mmpose#2187]
**Checklist**

- [x] 1. I have searched related issues but cannot get the expected help.

- [x] 2. The bug has not been fixed in the latest version.

**Describe the bug**
I get the following error message: 
```
Traceback (most recent call last):
  File "demo/bottom_up_img_demo.py", line 9, in <module>
    from mmpose.apis import (inference_bottom_up_pose_model, init_pose_model,
ImportError: cannot import name 'inference_bottom_up_pose_model' from 'mmpose.apis' 
```

**Reproduction**

- I installed the mmpose version 1.0.0 by following the instructions in [the document ](https://mmpose.readthedocs.io/en/latest/installation.html) yesterday, and confirmed that the inference of the pose labels work perfectly. 
- This morning, I installed Spyder 4.2.5 in the same environment where the mmpose is installed. Unfortunately, that caused downgrading of Parso, leading to the error I mentioned earlier. To fix this, I uninstalled Spyder, and did all the mmpose installation again from scratch. I also reinstalled Parso to the original version. 
- However, when I run a inference command, I get the error. The command I ran is show below: 
```
python demo/bottom_up_img_demo.py     \
tests/data/coco/000000000785.jpg     \
td-hm_hrnet-w48_8xb32-210e_coco-256x192.py    \
 hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth    \
 --out-file vis_results.jpg     --draw-heatmap
```

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmpose/utils/collect_env.py` to collect necessary environment information and paste it here.
 It caused an error message: 
```
Traceback (most recent call last):
  File "mmpose/utils/collect_env.py", line 3, in <module>
    from mmcv.utils import get_git_hash
ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' 
```

2. You may add addition that may be helpful for locating the problem, such as

- How you installed PyTorch \[e.g., pip, conda, source\]
   I installed PyTorch by 
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

**Comment by dkobayas-cyber** [comment]
After creating a new environment and doing every from scratch, the infernece worked fine.

**Comment by XiaoyinFeng** [comment]
> After creating a new environment and doing every from scratch, the infernece worked fine.

Congratulations on solving this problem, Could you provide your version of mmcv, mmdet and mmpose I have the same problem as you, thank you

**Comment by ruezzZZ** [comment]
After I configured the corresponding environment according to the official installation document, the following error occurred when running the demo.

**(mmpose_py38) D:\CodeTest\Code\gitclone\mmpose>python demo/image_demo.py tests/data/coco/000000000785.jpg td-hm_hrnet-w48_8xb32-210e_coco-256x192.py td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth --out-file vis_results.jpg --draw-heatmap
D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "demo/image_demo.py", line 8, in <module>
    from mmpose.apis import inference_topdown, init_model
  File "d:\codetest\code\gitclone\mmpose\mmpose\apis\__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottomup,
  File "d:\codetest\code\gitclone\mmpose\mmpose\apis\inference.py", line 17, in <module>
    from mmpose.models.builder import build_pose_estimator
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\__init__.py", line 8, in <module>
    from .heads import *  # noqa
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\heads\__init__.py", line 11, in <module>
    from .transformer_heads import EDPoseHead
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\heads\transformer_heads\__init__.py", line 2, in <module>
    from .edpose_head import EDPoseHead
  File "d:\codetest\code\gitclone\mmpose\mmpose\models\heads\transformer_heads\edpose_head.py", line 14, in <module>
    from mmcv.ops import MultiScaleDeformableAttention
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\APPSoftWare\Anaconda\AnacondaFolder\envs\mmpose_py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。**

I am sorry that I have not been able to solve this problem in various web pages. Now my installation package is posted. Could you please help me find out the reason? My sincere thanks to all of you！

# Name                    Version                   Build  Channel
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.15.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
blas                      1.0                         mkl
brotli-python             1.0.9            py38hd77b12b_7
ca-certificates           2023.12.12           haa95532_0
certifi                   2024.2.2         py38haa95532_0
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0
chumpy                    0.70                     pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
coverage                  7.4.3                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cuda-cccl                 12.4.99                       0    nvidia
cuda-cudart               11.8.89                       0    nvidia
cuda-cudart-dev           11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-libraries-dev        11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvrtc-dev            11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-profiler-api         12.4.99                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cudatoolkit               11.8.0               hd77b12b_0
cudnn                     8.9.2.26               cuda11_0
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.9                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
filelock                  3.13.1           py38haa95532_0
flake8                    7.0.0                    pypi_0    pypi
fonttools                 4.49.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
fsspec                    2024.2.0                 pypi_0    pypi
git                       2.40.1               haa95532_1
gmpy2                     2.1.2            py38h7f96b67_0
idna                      3.4              py38haa95532_0
importlib-metadata        7.0.2                    pypi_0    pypi
importlib-resources       6.3.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
interrogate               1.5.0                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jinja2                    3.1.3            py38haa95532_0
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
json-tricks               3.17.3                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcurand                 10.3.5.119                    0    nvidia
libcurand-dev             10.3.5.119                    0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libjpeg-turbo             2.0.0                h196d8e1_0
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libwebp-base              1.3.2                h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.5.2                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3            py38h2bbff1b_0
matplotlib                3.7.5                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.8            py38h2bbff1b_0
mkl_random                1.2.4            py38h59b6b97_0
mmcv                      2.1.0                    pypi_0    pypi
mmdet                     3.3.0                    pypi_0    pypi
mmengine                  0.10.3                   pypi_0    pypi
mmpose                    1.3.1                     dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.3.0            py38haa95532_0
munkres                   1.1.4                    pypi_0    pypi
networkx                  3.1              py38haa95532_0
numpy                     1.24.3           py38h79a8e48_1
numpy-base                1.24.3           py38h8a87ada_1
opencv-python             4.9.0.80                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.13               h2bbff1b_0
openxlab                  0.0.35                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parameterized             0.9.0                    pypi_0    pypi
pillow                    10.2.0           py38h2bbff1b_0
pip                       23.3.1           py38haa95532_0
platformdirs              4.2.0                    pypi_0    pypi
pluggy                    1.4.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
pytest                    8.1.1                    pypi_0    pypi
pytest-runner             6.0.1                    pypi_0    pypi
python                    3.8.18               h1aa4202_0
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   2.2.1           py3.8_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.4                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.1            py38h2bbff1b_0
regex                     2023.12.25               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   2.0.3                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
sympy                     1.12             py38haa95532_0
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
termcolor                 2.4.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torchaudio                2.2.1                    pypi_0    pypi
torchvision               0.17.1                   pypi_0    pypi
tqdm                      4.65.2                   pypi_0    pypi
typing_extensions         4.9.0            py38haa95532_1
tzdata                    2024.1                   pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
xdoctest                  1.1.3                    pypi_0    pypi
xtcocotools               1.14.3                   pypi_0    pypi
xz                        5.4.6                h8cc25b3_0
yaml                      0.2.5                he774522_0
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0
