### ISSUE TITLE
How to replace bbox in coco-annotations with COCO_val2017_detections_AP_H_56_person.json

### ISSUE THREAD

**Issue by ThomaswellY** [open-mmlab/mmpose#2199]
### Discussed in https://github.com/open-mmlab/mmpose/discussions/2198

<div type='discussions-op-text'>

<sup>Originally posted by **ThomaswellY** April 11, 2023</sup>
Hi ! I have been using mmpose 1.X recently, and there is a question i wanna search for help. 
When I was using topdown_regression algorithm with coco datasets, what if i set 'bbox_file=None', and replace the bbox in coco-annotaions with the bbox for the highest score in COCO_val2017_detections_AP_H_56_person.json,.
Would that be equal to setting 'bbox_file=COCO_val2017_detections_AP_H_56_person.json' ? 
If not, how can I reach the same result while setting bbox_file to None? Thanks in advance !</div>

**Comment by Ben-Louis** [comment]
Hi, thanks for using MMPose.  It looks like you can't really skip using the `bbox_file` and still get the same results. This is because the score for each instance, which is associated with the bounding boxes, depends on both the bbox score and the predicted keypoint scores. Unfortunately, you can't determine these scores before you run the validation process. By the way, have you run into any issues using the "COCO_val2017_detections_AP_H_56_person.json" file?

**Comment by Ben-Louis** [comment]
This is certainly quite a surprising result. In all of our experiments, we've observed better results with human-annotated bounding boxes. If you don't mind, could you please share some details about the model you're using? We would be very interested to learn more.

**Comment by ThomaswellY** [comment]
No problem, if there's anything derve sharing, I'll put it up to disscussion. Thanks a lot my friend~
