### ISSUE TITLE
About 'scale'. 

### ISSUE THREAD

**Issue by xiahongfu** [open-mmlab/mmpose#2209]
请问mmpose里的scale代表什么含义。我发现我所有bbox的scale的两个值都是完全一样的（不同bbox之间的scale是不同的）。请问这正常吗？
What does 'scale' in mmpose mean? I found that both values of the scale for all my bboxes are exactly the same (the scale varies from bbox to bbox). Is this normal, please? 

我数据集里的所有图片大小都是(455, 346)，heatmap输出都是（64， 64）。
In my dataset, all the images size is same(455, 346), but the bbox are not same.

**Comment by xiahongfu** [comment]
Thank you for your reply. The "scale" is in meta_keys in train_pipeline and test_pipeline in config file.
```python
train_pipeline = [
    ...
    dict(
        type='Collect',
        keys=['img', 'target', 'target_weight'],
        meta_keys=[
            'image_file', 'joints_3d', 'joints_3d_visible', 'center', 'scale',
            'rotation', 'bbox_score', 'flip_pairs'
        ]),
]

val_pipeline = [
    ...
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score',
            'flip_pairs'
        ]),
]
```

> Thank you for using MMPose. Could you please specify which "scale" you are referring to? There are multiple instances of "scale" within the code.

**Comment by Ben-Louis** [comment]
Since you are using MMPose 0.x, you can refer to [TopDownGetBboxCenterScale](https://github.com/open-mmlab/mmpose/blob/3b8173463c4ecdcd3d82d566254bb2ae2eb0cc07/mmpose/datasets/pipelines/top_down_transform.py#L15) for calculating the 'scale' for each bounding box. The scale will be adjusted to maintain a fixed aspect ratio. If this ratio is 1, then scale_x should be equal to scale_y.

**Comment by xiahongfu** [comment]
Thank you, I understand.
