### ISSUE TITLE
KeyError: 'TopdownPoseEstimator is not in the model registry.

### ISSUE THREAD

**Issue by Godoakos** [open-mmlab/mmpose#2440]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmpose/issues) and [Discussions](https://github.com/open-mmlab/mmpose/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmpose).

### Environment

**python -c "from mmpose.utils import collect_env; print(collect_env())**

```
OrderedDict([('sys.platform', 'linux'), ('Python', '3.9.16 (main, Mar  8 2023, 14:00:05) [GCC 11.2.0]'), ('CUDA available', True), ('numpy_random_seed', 2147483648), ('GPU 0', 'NVIDIA GeForce RTX 4080'), ('CUDA_HOME', '/usr/local/cuda-11.8'), ('NVCC', 'Cuda compilation tools, release 11.8, V11.8.89'), ('GCC', 'gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0'), ('PyTorch', '2.0.1'), ('PyTorch compiling details', 'PyTorch built with:\n  - GCC 9.3\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.7\n  - Magma 2.6.1\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.15.2'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.3'), ('MMPose', '1.0.0+')])
```
**pip list | grep mm**
```
mmcv                2.0.0
mmdet               3.0.0
mmengine            0.7.3
mmpose              1.0.0
```

### Reproduces the problem - code sample

```python
from mmpose.apis import init_model as init_pose_estimator

config = f'{CONFIG_ROOT}/hrnet/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py'
checkpoint = f'{CHECKPOINT_ROOT}/hrnet/hrnet_w32-36af842e.pth'

model_pose = init_pose_estimator(config,
                                 checkpoint,
                                 device='cuda:0')
```

### Reproduces the problem - command or script

The above code sample with {CONFIG_ROOT} and {CHECKPOINT_ROOT} set appropriately.

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/godoakos/PycharmProjects/dualtask-e2e/sandbox.py", line 7, in <module>
    model_pose = init_pose_estimator(config,
  File "/home/godoakos/miniconda3/envs/dualtask/lib/python3.9/site-packages/mmpose/apis/inference.py", line 101, in init_model
    model = build_pose_estimator(config.model)
  File "/home/godoakos/miniconda3/envs/dualtask/lib/python3.9/site-packages/mmpose/models/builder.py", line 35, in build_pose_estimator
    return POSE_ESTIMATORS.build(cfg)
  File "/home/godoakos/miniconda3/envs/dualtask/lib/python3.9/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/godoakos/miniconda3/envs/dualtask/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/godoakos/miniconda3/envs/dualtask/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'TopdownPoseEstimator is not in the model registry. Please check whether the value of `TopdownPoseEstimator` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

### Additional information

_td-hm_hrnet-w32_8xb64-210e_coco-256x192.py_ is from the mmpose git repo, its contents are:

``` python
_base_ = ['../_base_/default_runtime.py']

# runtime
train_cfg = dict(max_epochs=210, val_interval=10)

# optimizer
optim_wrapper = dict(optimizer=dict(
    type='Adam',
    lr=5e-4,
))

# learning policy
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001,
        by_epoch=False),  # warm-up
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[170, 200],
        gamma=0.1,
        by_epoch=True)
]

# automatically scaling LR based on the actual training batch size
auto_scale_lr = dict(base_batch_size=512)

# hooks
default_hooks = dict(checkpoint=dict(save_best='coco/AP', rule='greater'))

# codec settings
codec = dict(
    type='MSRAHeatmap', input_size=(192, 256), heatmap_size=(48, 64), sigma=2)

# model settings
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(32, 64)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(32, 64, 128)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(32, 64, 128, 256))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmpose/'
            'pretrain_models/hrnet_w32-36af842e.pth'),
    ),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=17,
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=codec),
    test_cfg=dict(
        flip_test=True,
        flip_mode='heatmap',
        shift_heatmap=True,
    ))

# base dataset settings
dataset_type = 'CocoDataset'
data_mode = 'topdown'
data_root = 'data/coco/'

# pipelines
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=64,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_train2017.json',
        data_prefix=dict(img='train2017/'),
        pipeline=train_pipeline,
    ))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_val2017.json',
        bbox_file='data/coco/person_detection_results/'
        'COCO_val2017_detections_AP_H_56_person.json',
        data_prefix=dict(img='val2017/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = val_dataloader

# evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/person_keypoints_val2017.json')
test_evaluator = val_evaluator
```

**Comment by Godoakos** [comment]
I ran into this issue after updating the open-mmlab components to the new releases - I wonder if anyone else encountered this with HRNet?

**Comment by Ben-Louis** [comment]
Sorry, but we couldn't reproduce this bug. Have you tweaked the mmpose code at all? Were there any other errors besides the KeyError?

**Comment by Godoakos** [comment]
Thank you for the quick response, I was just typing the below up when you replied.
I think I've found the issue - I was pointing at the `default_runtime.py` from mmdet instead of mmpose in _td-hm_hrnet-w32_8xb64-210e_coco-256x192.py_:

The `default_runtime.py` from mmdet which caused the issue:
```python
default_scope = 'mmdet'

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=1),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='DetVisualizationHook'))

env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'),
)

vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='DetLocalVisualizer', vis_backends=vis_backends, name='visualizer')
log_processor = dict(type='LogProcessor', window_size=50, by_epoch=True)

log_level = 'INFO'
load_from = None
resume = False
```
Replaced with the mmpose `default_runtime.py`:
```python
default_scope = 'mmpose'

# hooks
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=10),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='PoseVisualizationHook', enable=False),
)

# custom hooks
custom_hooks = [
    # Synchronize model buffers such as running_mean and running_var in BN
    # at the end of each epoch
    dict(type='SyncBuffersHook')
]

# multi-processing backend
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'),
)

# visualizer
vis_backends = [
    dict(type='LocalVisBackend'),
    # dict(type='TensorboardVisBackend'),
    # dict(type='WandbVisBackend'),
]
visualizer = dict(
    type='PoseLocalVisualizer', vis_backends=vis_backends, name='visualizer')

# logger
log_processor = dict(
    type='LogProcessor', window_size=50, by_epoch=True, num_digits=6)
log_level = 'INFO'
load_from = None
resume = False

# file I/O backend
backend_args = dict(backend='local')

# training/validation/testing progress
train_cfg = dict(by_epoch=True)
val_cfg = dict()
test_cfg = dict()
```
After making sure to use the mmpose `default_runtime.py` everything is working fine.

**Comment by Ben-Louis** [comment]
Thank you for your feedback! The error `'TopdownPoseEstimator is not in the model registry` primarily occurred because the default scope was incorrectly set to 'mmdet', whereas it should have been 'mmpose'. This is where `TopdownPoseEstimator` is registered.

**Comment by Mr-bor** [comment]
我遇到了同样的问题，但我是转换face到ONNX格式时出现的
按照上述方法，我将Lib\site-packages\mmdet\.mim\configs\_base_\default_runtime.py修改为mmpose的内容，但仍会问题。于是我尝试将该环境下所有default_runtime.py都改成了mmpose的内容，但是并没有什么用
请问有什么办法吗？

**Comment by Mr-bor** [comment]
我也遇到了相似的问题

根据教程安装
https://mmpose.readthedocs.io/en/latest/installation.html
https://mmdeploy.readthedocs.io/en/latest/get_started.html#installation

# Environment
其中，mmdeploy和mmpose都是dev 1.x版本
Package    Version    Source
---------  ---------  -----------------------------------------
mmcv       2.0.0      https://github.com/open-mmlab/mmcv
mmdet      3.0.0      https://github.com/open-mmlab/mmdetection
mmengine   0.7.4      https://github.com/open-mmlab/mmengine
mmpose     1.0.0      e:\study\mmpose\mmpose

# Additional information
在转换face模型时，出现了错误
模型config：
https://github.com/open-mmlab/mmpose/blob/dev-1.x/projects/rtmpose/rtmpose/face_2d_keypoint/rtmpose-m_8xb256-120e_lapa-256x256.py


目录结构
|-----
- rtmpose_test
- mmpose
- mmdeploy
- mmdeploy-1.1.0-windows-amd64
- rtmpose/权重

# Reproduces the problem - code sample
'''
from mmdeploy.apis import torch2onnx
from mmdeploy.backend.sdk.export_info import export2SDK

img = 'rtmpose_test/test1.jpg'
work_dir = 'work_dir/onnx/resnet'
save_file = 'end2end.onnx'
deploy_cfg = 'mmdeploy/configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py'
model_cfg = 'mmpose/projects/rtmpose/rtmpose/face_2d_keypoint/rtmpose-m_8xb256-120e_lapa-256x256.py'
model_checkpoint = 'rtmpose/rtmpose-m_simcc-face6.pth'
device = 'cpu'

# 1. convert model to onnx
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  model_checkpoint, device)

# 2. extract pipeline info for sdk use (dump-info)
export2SDK(deploy_cfg, model_cfg, work_dir, pth=model_checkpoint, device=device)

'''

# Reproduces the problem - error message
‘’‘
C:\Users\15443\AppData\Roaming\Python\Python38\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
06/15 21:04:14 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
06/15 21:04:14 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "e:\study\mmpose\mmpose\mmpose\models\pose_estimators\topdown.py", line 47, in __init__
    super().__init__(
  File "e:\study\mmpose\mmpose\mmpose\models\pose_estimators\base.py", line 47, in __init__
    self.backbone = MODELS.build(backbone)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 442, in get
    self.import_from_location()
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 376, in import_from_location
    import_module(loc)
  File "E:\Applications\anaconda\envs\openmmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..layers import CSPLayer
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdet\models\layers\__init__.py", line 3, in <module>
    from .bbox_nms import fast_nms, multiclass_nms
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdet\models\layers\bbox_nms.py", line 5, in <module>
    from mmcv.ops.nms import batched_nms
  File "C:\Users\15443\AppData\Roaming\Python\Python38\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\15443\AppData\Roaming\Python\Python38\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\15443\AppData\Roaming\Python\Python38\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "E:\Applications\anaconda\envs\openmmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdeploy\apis\pytorch2onnx.py", line 63, in torch2onnx
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmdeploy\codebase\base\task.py", line 120, in build_pytorch_model
    model = MODELS.build(model)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "E:\Applications\anaconda\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 144, in build_from_cfg
    raise type(e)(
ImportError: class `TopdownPoseEstimator` in mmpose/models/pose_estimators/topdown.py: DLL load failed while importing _ext: 找不到指定的模块。

'''
