### ISSUE TITLE
[Docs] How to inference model for AP10K dataset type?

### ISSUE THREAD

**Issue by mzillag** [open-mmlab/mmpose#2696]
### 📚 The doc issue

I have trained the model with config (rtmpose-m_8xb64-210e_ap10k-256x256.py) for mmpose. On output I have two files with weights:
epoch_207.pth,
best_coco_AP_epoch_177.pth -  (if I understand correctly, it's 2 different models. because best_coco.pth weights 2 times smaller than epoch_n.pth files)

I expected that I would find inference options with flexible usage for python api for such cases [here](https://mmpose.readthedocs.io/en/latest/user_guides/inference.html#python-api-more-flexible-and-customizable), but I didn’t find them there. Is it possible to add explanation on how to use those? Also, interesting if I could get class label from detection model?

**Comment by mzillag** [comment]
Also, I want to change amount of classes for animals, but I can't find a way to do this.

**Comment by Ben-Louis** [comment]
1) The two `.pth` files are both checkpoints for animal pose estimation model. The `best_coco_AP_epoch_177.pth` is smaller because the parameters of optimizer are cleaned. 
2) To perform animal pose estimation model inference, please refer to [2d_animal_demo](https://github.com/open-mmlab/mmpose/blob/main/demo/docs/en/2d_animal_demo.md)
