### ISSUE TITLE
[Feature] How to run tracking config

### ISSUE THREAD

**Issue by enesdoruk** [open-mmlab/mmpose#2884]
### What is the feature?

Hi, how can I run tracking configs for demo scripts/

**Comment by Ben-Louis** [comment]
Hello, can you please provide more information about what is meant by "tracking configs"?

**Comment by enesdorukadastec** [comment]
I want to run pose tracking model and i want to use tracking model instead of detection, In demo folder there are two tracking configs under mmtracking_cfg (mmlab/mmpose/blob/main/demo/mmtracking_cfg/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py,  demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py)), How to run these configs using inferencer_demo script

**Comment by Ben-Louis** [comment]
Unfortunately, these tracking models are not supported in the new version. However, you can still use mmpose 0.x for these tracking methods. For more information, please visit https://mmpose.readthedocs.io/en/0.x/demo.html#d-pose-tracking-demo.
