### ISSUE TITLE
About training HMR models

### ISSUE THREAD

**Issue by NoLookDefense** [open-mmlab/mmpose#598]
Hello. I am going to train HMR model, but I found the config.py is different in HMR task is different, because it didn't need to assign the dataset type. It seems that the training will begin only when all the related datasets are well-prepared.
But what should I do if I want to train HMR task with MPI-INF-3DHP dataset only? Whether 3DWP dataset is currently supported now?

**Comment by NoLookDefense** [comment]
Also, are there any reference about explaining the dataset of 3D HMR and SMPL? I found that lots of components are needed to be downloaded, but I feel confused about their relationship

**Comment by zengwang430521** [comment]
Hi, for HMR, we use the datasets mentioned in the paper. To make utilize multiple datasets, we followed the setting of [SPIN](https://github.com/nkolot/SPIN) to preprocess the annotation file first. You can find these processed annotation files directly from SPIN project.
MPI-INF-3DHP dataset is supported now. In order to only use  MPI-INF-3DHP dataset, you need to:
1. Preprocess 3DHP dataset following the process of SPIN to get annotation file and extract images.
2. Modify the config file. Used datasets are set by [these lines](https://github.com/open-mmlab/mmpose/blob/1f29723b5e2769c3c676ede6463dc7d26561271a/configs/mesh/hmr/hmr_res50_224x224.py#L114-L148). You can only delete other datasets and only remain the lines about 3DHP. In addition, you also need to modify the 'partition' to '[1]'.

**Comment by NoLookDefense** [comment]
> Hi, for HMR, we use the datasets mentioned in the paper.
> 
> To make utilize multiple datasets, we followed the setting of [SPIN](https://github.com/nkolot/SPIN) to preprocess the annotation file first. You can find these processed annotation files directly from SPIN project.
> 
> MPI-INF-3DHP dataset is supported now. In order to only use MPI-INF-3DHP dataset, you need to:
> 
> 1. Preprocess 3DHP dataset following the process of SPIN to get annotation file and extract images.
> 2. Modify the config file. Used datasets are set by [these lines](https://github.com/open-mmlab/mmpose/blob/1f29723b5e2769c3c676ede6463dc7d26561271a/configs/mesh/hmr/hmr_res50_224x224.py#L114-L148). You can delete other datasets and only remain the lines about 3DHP. In addition, you also need to modify the 'partition' to '[1]'.

Thank you. BTW, if I only want to train with a single dataset, what should I edit?

**Comment by NoLookDefense** [comment]
Thank you for your reply.
BTW, I also saw the keyword "adversarial_dataset". I wonder whether I should comment it if I only want to train 3DHP?

**Comment by NoLookDefense** [comment]
Thanks for your reply. 
I tried it, but an error occurs:

Traceback (most recent call last):
File "tools/train.py", line 166, in <module>
main()
File "tools/train.py", line 162, in main
meta=meta)
File "/home/jack/Desktop/mmpose/mmpose/apis/train.py", line 125, in train_model
val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
File "/home/jack/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/utils/config.py", line 43, in __getattr__
raise ex
AttributeError: 'ConfigDict' object has no attribute 'val'

It seems that the config file lacks something?

**Comment by zengwang430521** [comment]
Hi, when training HMR model, we do not use validation set. So we need to add '--no-validate' setting.

**Comment by NoLookDefense** [comment]
Thank you! It works
