### ISSUE TITLE
Visualize 3d pose

### ISSUE THREAD

**Issue by NoLookDefense** [open-mmlab/mmpose#648]
Hello. Are there any demos which can project 3d pose or mesh to 2d plane?

**Comment by jin-s13** [comment]
We have plans to support 3d pose/mesh visualization. Still working on that.

**Comment by NoLookDefense** [comment]
Thank you! May I have your roadmap? I wonder the approximate time.

**Comment by ly015** [comment]
3d pose visualization will be supported this week with a demo based on the pose lifter model. As for 3d mesh visualization, we don't have a plan yet, please stay tuned to our iteration plan.

**Comment by NoLookDefense** [comment]
Thank you. Have a nice day!

**Comment by NoLookDefense** [comment]
Hello. I wonder whether the code of 3d pose visualisation ready?

**Comment by jin-s13** [comment]
Almost ready. Check this #653

**Comment by NoLookDefense** [comment]
Thank you I saw it. Are there any demo codes or instructions to use it?

**Comment by ly015** [comment]
This PR has been merged into master. Please check this: https://github.com/open-mmlab/mmpose/blob/master/demo/docs/3d_human_pose_demo.md

**Comment by NoLookDefense** [comment]
Thank you. I have run it successfully.
But it seems that there is not a projection from 3d keypoints to 2d plane? I found that the 2d keypoint is loaded from annotation file and there's not a conversion between 2d and 3d.
I wonder that will the scripts of projection from 3d to 2d will be provided? For example, I estimated the 3d pose from the simple-baseline-3d model, and project it to the origin images. Something like this

**Comment by ly015** [comment]
Yes in the demo we use 2d keypoints for visualization instead of projecting 3d keypoints back to the image. You can check out the [SimpleCamera](https://github.com/open-mmlab/mmpose/blob/master/mmpose/core/camera/single_camera.py) if you need to do the 3d-to-2d projection. It provides keypoint transformations among the world space, camera space, and image space. The human3.6m camera parameters can be found [here](https://github.com/open-mmlab/mmpose/blob/master/tests/data/h36m/cameras.pkl).

Please note that the simple-baseline-3d model does not predict global trajectories, but only the relative joints in the camera space. So if you directly project 3d keypoints back to the image space, they will not align with the image.

**Comment by NoLookDefense** [comment]
Clear. BTW, will you provide some any runnable demo for running the code in SimpleCamera? I am afraid I will make some mistakes in the data format

**Comment by ly015** [comment]
Currently, the SimpleCamera class has not been used in any model or script. It is used in a transformation operator in the dataset pipeline, which is designed to apply transformations in data preprocessing. For example, it allows us to train 2d-to-3d models without 2d annotations, or to apply augmentations (e.g. random rotation, transformation, or joint movement) in the 3d space and obtain corresponding 2d keypoints.

You can check it [here](https://github.com/open-mmlab/mmpose/blob/d0d8786c32f96663a54a685292aae31fa59ac7c7/mmpose/datasets/pipelines/pose3d_transform.py#L225) and its [unittest](https://github.com/open-mmlab/mmpose/blob/master/tests/test_pipelines/test_pose3d_transform.py) may also be helpful.

**Comment by NoLookDefense** [comment]
Thank you! But I cannot use the script 
https://github.com/open-mmlab/mmpose/blob/master/tests/test_pipelines/test_pose3d_transform.py
straightly. How can I use the unit test?

**Comment by innerlee** [comment]
> How can I use the unit test?

By looking at it :)
