### ISSUE TITLE
Smaller Image Size Higher HR Net

### ISSUE THREAD

**Issue by lmarschall** [open-mmlab/mmpose#675]
Hey Guys,

on my current project im trying to achieve real time performance with system on chips hardware. Therefore i was validating the higher_hrnet32_coco_512x512 with my integrated mx350 nvidia gpu. The performance was as expected very slow, with ca 0.25 s per frame.

To improve speed i now tweaked the image size in the config file and validated the quality of the pose estimation, which was quite good.

So the question appeared, if it is good practice to just alter the image size and can i train this model with smaller image size setting.

Best Regards,

Luke

**Comment by jin-s13** [comment]
1. Have you tried these [tips](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_human_pose_demo.md#speed-up-inference) to speed up inference? 
2. Yes. The bottom-up model is robust to different image sizes, which is why we may use multi-scale testing for inference. Of course, training with smaller image size is ok.

**Comment by lmarschall** [comment]
Hey @jin-s13,

thank you for the quick answer.

Maybe one more question to approve my methodology. Is it possible, to take the 512x512 checkpoints, alter the config and then finetune the model, or should this happen with the default config file?

**Comment by jin-s13** [comment]
I think finetuning the model (with different input size) is also applicable. You can try it.
