### ISSUE TITLE
Training Interhand2.6M for 3D pose

### ISSUE THREAD

**Issue by wbhu** [open-mmlab/mmpose#879]
Hi,

I met the following error when I train the 3D hand pose with the config file of _configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/res50_interhand3d_all_256x256.py_.

`/site-packages/mmpose/models/detectors/base.py", line 59, in _parse_losses
    f'{loss_name} is not a tensor or list of tensors or float')
TypeError: acc_classification is not a tensor or list of tensors or float`

This error is not occurred at the beginning, but after ~200 iterations. Is there any hints about the reason? 

Thanks.

**Comment by zengwang430521** [comment]
Hi,  I'm sorry that this error may be caused by a bug in [interhnad3d head](https://github.com/open-mmlab/mmpose/blob/0839f847bf9f01c2697c89841879b1022e071339/mmpose/models/heads/interhand_3d_head.py#L365).

We will fix the bug in [pull_890](https://github.com/open-mmlab/mmpose/pull/890) and will train the model again to check whether the bug is fixed.

**Comment by wbhu** [comment]
Thanks 👍
