### ISSUE TITLE
[2D Human Whole-Body Pose]: Non-separate toe markers 

### ISSUE THREAD

**Issue by antoinefalisse** [open-mmlab/mmpose#921]
Hi, I've been playing around with the [2D Human Whole-Body Pose Demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_wholebody_pose_demo.md). I'm a bit confused regarding the toe markers. On the videos I obtain (as well as on the demo video), it seems that the two toe markers (big and small toes) are on top of each other, whereas on the [COCO-WholeBody homepage](https://github.com/jin-s13/COCO-WholeBody/), they appear clearly separate both on the [test image](https://github.com/jin-s13/COCO-WholeBody/blob/master/imgs/Fig1_example.png) and on the [descriptive image](https://github.com/jin-s13/COCO-WholeBody/blob/master/imgs/Fig2_anno.png). When looking into the results in more details, I see almost similar 2D coordinates for the big and small toes, ruling out rendering issues. **Is there an explanation for having non-separate toe markers when running [2D Human Whole-Body Pose Demo](https://github.com/open-mmlab/mmpose/blob/master/demo/docs/2d_wholebody_pose_demo.md)?**

Thanks a lot for developing mmpose, it is awesome!

**Comment by luminxu** [comment]
Thank you for putting forward the discussion. We have visualized the annotations of COCO-WholeBody and checked our codes for whole-body pose estimation, which verifies that there is no bug for data and codes. However, the trained models still output extremely close (not exactly the same) coordinates for the big and small toes. We think this is because the two toes are very close in most cases, especially the side-view, and it is hard for the whole-body models to learn to distinguish the two toes.

**Comment by jin-s13** [comment]
We also noticed some models are able to distinguish the two keypoints. 
This [PR](https://github.com/open-mmlab/mmpose/issues/822) provides some example visualization results. We can see that the two toes are distinguishable. 

I think this is a good direction to explore more.

**Comment by antoinefalisse** [comment]
Sorry I forgot to respond. Thanks for the answers!
