### ISSUE TITLE
VideoPose3D performance

### ISSUE THREAD

**Issue by wbhu** [open-mmlab/mmpose#938]
Hi,

I noticed that the MPJPE of the reimplemented VideoPose3D is 47.9mm with 243 CPN frames as input, while the paper reported MPJPE  is 46.8mm. Is there any difference between the reimplemented version and the official one?

Best,
Wenbo

**Comment by ly015** [comment]
Hi,

Thanks for the question. The difference is probably because that the original implementation performed test-time augmentation (horizontal flip), while we did not. As you can see in Table 5 of the paper, when removing the test-time augmentation, their performance is similar to ours.

Another difference is that the original implementation excluded `S11-Direction` from the test set (https://github.com/facebookresearch/VideoPose3D/blob/main/data/prepare_data_2d_h36m_generic.py#L71), while we did not.

**Comment by wbhu** [comment]
Thanks for your quick response. It makes sense that flipping in the test stage can improve performance.

**Comment by wbhu** [comment]
Another question about memory consumption during training. I noticed that the 'workers_per_gpu' is set to 0 in the config file. In this configuration, the bottleneck of the training is the I/O time on my machine. So I modified it to 4 for faster training (4 GPUs). But when doing so, the memory consumption is too large (> 128GB). If I understood correctly, the dataset object only maintains the 2D and 3D poses, which shouldn't consume so much memory. Could you please give me some hints on how to speed up the I/O during training?

Thanks

**Comment by ly015** [comment]
The original h36m data have a relatively large fps of 50. So it seems common practice to use a downsampled version of 10 fps to reduce the memory consumption and experiment time. If you are using the full version data, maybe you can consider switching to downsampled version for quick experiments. It can be set in our data preparation tool: https://github.com/open-mmlab/mmpose/blob/31c1e102bb29bdad91acb924c4597a2d3d4c6f6c/tools/dataset/preprocess_h36m.py#L397-L401

**Comment by wbhu** [comment]
Thanks for your suggestion.
